version: "3"
services:
  test:
    build: .
    ports:
      - "9500:9500"
    container_name: salesforce-connector-test
    environment:
      NODE_ENV: test
      SESSION_KEY: test
      PORT: 9500
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:8000
      MICROSERVICE_TOKEN: cttoken
      LOCAL_URL: http://127.0.0.1:9500
      HOST_IP: 127.0.0.1
      FASTLY_ENABLED: "false"
      SALESFORCE_URL: "fakeUrl"
      SALESFORCE_USERNAME: "fakeUser"
      SALESFORCE_PASSWORD: "fakePass"
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: true
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
