version: "3"
services:
  develop:
    build: .
    ports:
      - "9500:9500"
    container_name: salesforce-connector
    env_file:
      - dev.env
    command: develop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
